/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as PrivatePageRouteImport } from './routes/_private/page'
import { Route as publicGuestLayoutRouteImport } from './routes/(public)/_guest/layout'
import { Route as PrivateUsersPageRouteImport } from './routes/_private/users/page'
import { Route as PrivateProvidersPageRouteImport } from './routes/_private/providers/page'
import { Route as PrivateDashboardPageRouteImport } from './routes/_private/dashboard.page'
import { Route as PrivateSplatPageRouteImport } from './routes/_private/$.page'
import { Route as publicTermsPageRouteImport } from './routes/(public)/terms.page'
import { Route as publicGuestRegisterPageRouteImport } from './routes/(public)/_guest/register/page'
import { Route as publicGuestLoginPageRouteImport } from './routes/(public)/_guest/login/page'
import { Route as publicGuestRegisterSuccessPageRouteImport } from './routes/(public)/_guest/register/success/page'

const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatePageRoute = PrivatePageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const publicGuestLayoutRoute = publicGuestLayoutRouteImport.update({
  id: '/(public)/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateUsersPageRoute = PrivateUsersPageRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateProvidersPageRoute = PrivateProvidersPageRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateDashboardPageRoute = PrivateDashboardPageRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const PrivateSplatPageRoute = PrivateSplatPageRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => PrivateLayoutRoute,
} as any)
const publicTermsPageRoute = publicTermsPageRouteImport.update({
  id: '/(public)/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicGuestRegisterPageRoute = publicGuestRegisterPageRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => publicGuestLayoutRoute,
} as any)
const publicGuestLoginPageRoute = publicGuestLoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => publicGuestLayoutRoute,
} as any)
const publicGuestRegisterSuccessPageRoute =
  publicGuestRegisterSuccessPageRouteImport.update({
    id: '/register/success/',
    path: '/register/success/',
    getParentRoute: () => publicGuestLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PrivatePageRoute
  '/terms': typeof publicTermsPageRoute
  '/$': typeof PrivateSplatPageRoute
  '/dashboard': typeof PrivateDashboardPageRoute
  '/providers': typeof PrivateProvidersPageRoute
  '/users': typeof PrivateUsersPageRoute
  '/login': typeof publicGuestLoginPageRoute
  '/register': typeof publicGuestRegisterPageRoute
  '/register/success': typeof publicGuestRegisterSuccessPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PrivatePageRoute
  '/terms': typeof publicTermsPageRoute
  '/$': typeof PrivateSplatPageRoute
  '/dashboard': typeof PrivateDashboardPageRoute
  '/providers': typeof PrivateProvidersPageRoute
  '/users': typeof PrivateUsersPageRoute
  '/login': typeof publicGuestLoginPageRoute
  '/register': typeof publicGuestRegisterPageRoute
  '/register/success': typeof publicGuestRegisterSuccessPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/(public)/_guest': typeof publicGuestLayoutRouteWithChildren
  '/_private/': typeof PrivatePageRoute
  '/(public)/terms/': typeof publicTermsPageRoute
  '/_private/$/': typeof PrivateSplatPageRoute
  '/_private/dashboard/': typeof PrivateDashboardPageRoute
  '/_private/providers/': typeof PrivateProvidersPageRoute
  '/_private/users/': typeof PrivateUsersPageRoute
  '/(public)/_guest/login/': typeof publicGuestLoginPageRoute
  '/(public)/_guest/register/': typeof publicGuestRegisterPageRoute
  '/(public)/_guest/register/success/': typeof publicGuestRegisterSuccessPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/terms'
    | '/$'
    | '/dashboard'
    | '/providers'
    | '/users'
    | '/login'
    | '/register'
    | '/register/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/terms'
    | '/$'
    | '/dashboard'
    | '/providers'
    | '/users'
    | '/login'
    | '/register'
    | '/register/success'
  id:
    | '__root__'
    | '/_private'
    | '/(public)/_guest'
    | '/_private/'
    | '/(public)/terms/'
    | '/_private/$/'
    | '/_private/dashboard/'
    | '/_private/providers/'
    | '/_private/users/'
    | '/(public)/_guest/login/'
    | '/(public)/_guest/register/'
    | '/(public)/_guest/register/success/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  publicGuestLayoutRoute: typeof publicGuestLayoutRouteWithChildren
  publicTermsPageRoute: typeof publicTermsPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/': {
      id: '/_private/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PrivatePageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/(public)/_guest': {
      id: '/(public)/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicGuestLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/users/': {
      id: '/_private/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/providers/': {
      id: '/_private/providers/'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof PrivateProvidersPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/dashboard/': {
      id: '/_private/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PrivateDashboardPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_private/$/': {
      id: '/_private/$/'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PrivateSplatPageRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/(public)/terms/': {
      id: '/(public)/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof publicTermsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/_guest/register/': {
      id: '/(public)/_guest/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof publicGuestRegisterPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
    '/(public)/_guest/login/': {
      id: '/(public)/_guest/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicGuestLoginPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
    '/(public)/_guest/register/success/': {
      id: '/(public)/_guest/register/success/'
      path: '/register/success'
      fullPath: '/register/success'
      preLoaderRoute: typeof publicGuestRegisterSuccessPageRouteImport
      parentRoute: typeof publicGuestLayoutRoute
    }
  }
}

interface PrivateLayoutRouteChildren {
  PrivatePageRoute: typeof PrivatePageRoute
  PrivateSplatPageRoute: typeof PrivateSplatPageRoute
  PrivateDashboardPageRoute: typeof PrivateDashboardPageRoute
  PrivateProvidersPageRoute: typeof PrivateProvidersPageRoute
  PrivateUsersPageRoute: typeof PrivateUsersPageRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivatePageRoute: PrivatePageRoute,
  PrivateSplatPageRoute: PrivateSplatPageRoute,
  PrivateDashboardPageRoute: PrivateDashboardPageRoute,
  PrivateProvidersPageRoute: PrivateProvidersPageRoute,
  PrivateUsersPageRoute: PrivateUsersPageRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface publicGuestLayoutRouteChildren {
  publicGuestLoginPageRoute: typeof publicGuestLoginPageRoute
  publicGuestRegisterPageRoute: typeof publicGuestRegisterPageRoute
  publicGuestRegisterSuccessPageRoute: typeof publicGuestRegisterSuccessPageRoute
}

const publicGuestLayoutRouteChildren: publicGuestLayoutRouteChildren = {
  publicGuestLoginPageRoute: publicGuestLoginPageRoute,
  publicGuestRegisterPageRoute: publicGuestRegisterPageRoute,
  publicGuestRegisterSuccessPageRoute: publicGuestRegisterSuccessPageRoute,
}

const publicGuestLayoutRouteWithChildren =
  publicGuestLayoutRoute._addFileChildren(publicGuestLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  publicGuestLayoutRoute: publicGuestLayoutRouteWithChildren,
  publicTermsPageRoute: publicTermsPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
